version: '3.8'

services:
  postgres:
    container_name: postgres_nlw
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=certification_nlw
